name: 'Thank You Action'
description: 'Say "Thank You" on PRs'
author: Eder Ribeiro Ferreira

inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  PRIVATE_KEY:
    description: 'PRIVATE_KEY'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'